// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2zyEN4wbAvdpCs3a2xawX4
// Component: -F-RkKDSdI
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_all_in_1_website.module.css"; // plasmic-import: 2zyEN4wbAvdpCs3a2xawX4/projectcss
import sty from "./PlasmicTextInputEmail.module.css"; // plasmic-import: -F-RkKDSdI/css

export const PlasmicTextInputEmail__VariantProps = new Array();

export const PlasmicTextInputEmail__ArgProps = new Array();

function PlasmicTextInputEmail__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <input
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.input,
        projectcss.root_reset,
        sty.root
      )}
      placeholder={"Some placeholder"}
      size={1}
      type={"text"}
      value={"Email"}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"],
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTextInputEmail__ArgProps,
      internalVariantPropNames: PlasmicTextInputEmail__VariantProps,
    });

    return PlasmicTextInputEmail__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTextInputEmail";
  } else {
    func.displayName = `PlasmicTextInputEmail.${nodeName}`;
  }
  return func;
}

export const PlasmicTextInputEmail = Object.assign(
  // Top-level PlasmicTextInputEmail renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTextInputEmail
    internalVariantProps: PlasmicTextInputEmail__VariantProps,
    internalArgProps: PlasmicTextInputEmail__ArgProps,
  }
);

export default PlasmicTextInputEmail;
/* prettier-ignore-end */
